# Generated by Django 3.1.5 on 2021-01-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hno', models.CharField(max_length=100)),
                ('mobileno', models.IntegerField(max_length=100)),
                ('ownername', models.CharField(max_length=100)),
                ('uscno', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('child1', models.CharField(max_length=100)),
                ('child2', models.CharField(max_length=100)),
                ('child3', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('Mandal', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
            ],
        ),
    ]
