# Generated by Django 3.1.5 on 2021-01-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familydetails',
            name='age',
        ),
        migrations.RemoveField(
            model_name='familydetails',
            name='mobileno',
        ),
    ]
